# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  "php-7.1":
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: deps-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/php-coveralls -o coveralls.json -x coverage.xml
  "php-7.2":
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: deps-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/php-coveralls -o coveralls.json -x coverage.xml
  "php-7.3":
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: deps-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/php-coveralls -o coveralls.json -x coverage.xml
  "php-7.4":
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - restore_cache:
          keys: [deps-{{ checksum "composer.json" }}]
      - run: composer update -n --prefer-dist
      - save_cache:
          key: deps-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/php-coveralls -o coveralls.json -x coverage.xml

workflows:
  version: 2
  unittest:
    jobs:
      - "php-7.1"
      - "php-7.2"
      - "php-7.3"
      - "php-7.4"
